language: node_js
node_js:
  - "lts/*"
deploy:
  provider: s3
  access_key_id: "AKIAIIFFRH7YOQ7DTQWQ"
  secret_access_key:
    secure: "nd9qUIg1MArY0swOcUgEnJFGLB4CFJ9cnNGqJbeckOZKgYIfseMjL9R5gH44fTb5m5ul6tkw8841lyTkSnI9ARjsZHE/Jc/IAltEhpiqkAdTi5C/d0iAC/GJKtwvqBAIA4/EJZ1uVQ7DwzQH0wQgvEIqLU8EiRoE8nEpW4ci2OezQZe3vC/xLND/Ti4TYxsqKqVbq2BpvbMXX/wPxy5uU56dDAvOj62VkJAjjjBAg7tbqoWcQM4fZSi50Sq6VWuGEqZQdR9KslrXaYBWUF6on39XtmS++7C8S1IgP8DqIvZ9pTfYmi2+NymIdpckeJBnc9KlQlh+BYiVvxuOuRkUOYe8XzICCiGvfYd4iuiiVCcO7fIfnWSqCvtN4aScJfdUwSEKMNXHdyarDVkceZ5I+hIc8dhyB7yMN/zEW6FfeNsBkXlMmd7K92YCj7uEONM4LLXqodOHkiUILtOKAXZJKiRd51t/cdFPNSb/yVTBmtI76xHILCjl+ssglnJ1HhrObkyiJjYLO7sFljijN4nip0lycrhSTUGj5t5C0ZlJoM20Lg/GeZiFH3gDvTE790OFxqSCb/scrneDWLm8dl4A+NOgnn5FUhdYY0U0Td+ioTGI5N5iWFgzBfCuBCl1ZHoLHtyMFdfjdoYWTfHNlEBDR9Q3COA2ZmCLAEaAk3dB/b4="
  bucket: "smart-feature-toggles"
  skip_cleanup: true
  acl: public_read
  local_dir: __packages__/webpack-bundle/dist